language: objective-c
cache: cocoapods
osx_image: xcode7.3
podfile: XujcClient/Podfile

script:
  # - xctool -workspace XujcClient/XujcClient.xcworkspace -scheme XujcClient build test -sdk iphonesimulator CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
  - set -o pipefail && xcodebuild test -workspace XujcClient/XujcClient.xcworkspace -scheme XujcClient -sdk iphonesimulator9.3 | xcpretty
